### ISSUE TITLE
TranscodeError: Transcode probably did not succeed for file

### ISSUE THREAD

**Issue by TehMaster** [nwronski/batch-transcode-video#13]
Hello,

To set the stage - I am running Linux (windows subsystem for linux) on windows server 2019, and have all prereqs installed so that transcode-video works successfully (using bash from cmd.exe). However, when i try to run the batch-transcode-video i run into the below transcodeError. I have tried removing the extra transcode-video options, but get the same error.

I wonder if this is because of the file system differences? When running bash on windows i have to mount the patch as '/mnt/d/' instead of "d:\". Appreciate any help!

D:\_ToEncode>batch-transcode-video --input "_Test/" --output "transcoded/" --force "0:0:0:0" --diff -- --target 1800 --abr --preset slow --main-audio 1="Surround" --audio-width main=surround --ac3-bitrate 384

Starting batch operation...

Current:                                                      0.0913%
          File:   Test-File-2.mkv                             00h 07m 53s

Total:                                                        0.0913%
          Processed: 0.43 MB of 473.00 MB                     00h 17m 56s
          Status: ER: 1

Finished processing.

 - ERRORED:  Test-File-1.mkv
Error: [TranscodeError: Transcode probably did not succeed for file.]
File: Test-File-1.mkv

 - ERRORED:  Test-File-2.mkv
Error: [TranscodeError: Transcode probably did not succeed for file.]
File: Test-File-2.mkv

Summary:                                                      2 files
          Status: ER: 2
          Processed: 0.00 MB of 0.00 total MB                 0.00 MB/s
          Time:   Total 00h 00m 01s (Avg: 00h 00m 00s)

 => Finished with errors.

**Comment by nwronski** [comment]
I've tested things out using powershell on windows, with windows-style paths, but not with your setup. Could you run the same command with the `--debug` option and send me the output?

**Comment by TehMaster** [comment]
Sure. As a reference i went through the process below to get everything installed:
https://github.com/JMoVS/installing_video_transcoding_on_windows

 Here is the output:
D:\_ToEncode>batch-transcode-video --input "_Test/" --output "transcoded/" --force "0:0:0:0" --diff --debug -- --target 1800 --abr --preset slow --main-audio 1="Surround" --audio-width main=surround --ac3-bitrate 384

Starting batch operation...

stderr: C:/Ruby25-x64/bin/transcode-video: HandBrakeCLI not available

stderr: C:/Ruby25-x64/bin/transcode-video: HandBrakeCLI not available

Finished processing.

 - ERRORED:  Test-File-1.mkv
Error: [TranscodeError: Transcode probably did not succeed for file.]
File: Test-File-1.mkv

 - ERRORED:  Test-File-2.mkv
Error: [TranscodeError: Transcode probably did not succeed for file.]
File: Test-File-2.mkv


Summary:                                                      2 files
          Status: ER: 2
          Processed: 0.00 MB of 0.00 total MB                 0.00 MB/s
          Time:   Total 00h 00m 01s (Avg: 00h 00m 00s)

 => Finished with errors.

**Comment by nwronski** [comment]
Based on that output (`stderr: C:/Ruby25-x64/bin/transcode-video: HandBrakeCLI not available`), it looks like it cannot find the handbrake cli (`HandBrakeCLI`) in your `PATH`.

**Comment by TehMaster** [comment]
Appreciate your help! I installed everything natively on windows (instead of the linux on windows route), copied what i needed to a new /bin, and everything is working fine now. Count this one as user error. :)
