### ISSUE TITLE
Error with conflicting crop detection results

### ISSUE THREAD

**Issue by jdawg61** [nwronski/batch-transcode-video#15]
Hi, Nick. I'm just getting started with using this very useful tool and have run in to an issue where files aren't completing the transcode when conflicting crop detection results are found. The error log below was produced when I was attempting to transcode an mkv file to an mp4. Other files where no crops were suggested by HandbrakeCLI or ffmpeg have completed with no problems. Any ideas as to what is happening or what I might be doing wrong?

Thanks for your help and thank you for developing this great utility!

Starting batch operation...

Current:                                                      0.2258%
          File:   title_t00.mkv                               01h 07m 30s

Total:                                                        0.2258%
          Processed: 9.17 MB of 4059.00 MB                    01h 07m 31s
          Status:

Finished processing.

 - ERRORED:  title_t00.mkv
Error: [TranscodeError: Crop detection returned conflicting results: 0:0:8:2, 0:0:8:0.]
File: title_t00.mkv
transcode-video --crop 0:0:8:2 christmas_story\\title_t00.mkv
transcode-video --crop 0:0:8:0 christmas_story\\title_t00.mkv

Summary:                                                      1 file
          Status: ER: 1
          Processed: 0.00 MB of 0.00 total MB                 0.00 MB/s
          Time:   Total 00h 00m 10s (Avg: 00h 00m 00s)

 => Finished with errors.

**Comment by nwronski** [comment]
Thanks, I'm glad you're enjoying it! If you are seeing the conflicting crop results, you can make use of the `--force` option to either continue anyway (e.g., `--force 1`) or to manually specify a crop value (e.g., `--force '0:0:8:0'`). Here is the description of `--force` from the help (`batch-transcode-video --help`):

```
--force [crop]	[false] (Alias: -f)
		If you provide an actual crop value (e.g.:
		"0:0:0:0") as the argument for this option,
		then that crop value will be used for all videos.
		If you provide anything other than an actual
		crop value (e.g. 1) as the argument for this
		option, then when crop detection returns
		conflicting crop values it will just use the
		least extreme crop value and continue
		transcoding.
```

**Comment by jdawg61** [comment]
Thanks for the tip! I didn't expect a response on Labor Day weekend, but I'm glad to get it.
