### ISSUE TITLE
Disable crop detection in this script?

### ISSUE THREAD

**Issue by JMoVS** [nwronski/batch-transcode-video#5]
Transcode-video by now allows to pass crop detection parameters as well as a fallback crop to transcode-video directly. Is batch-transcode-video calling transcode-video with the --detect-crop auto option? Or is it manually calling detect-crop and then passing those arguments to transcode-video?

**Comment by nwronski** [comment]
IIRC, the default behavior is to run detect-crop for each file and use the value provided from that command when calling transcode-video. You can also override that behavior by passing a `--force` option with the crop value you'd like to use and then all videos in the batch are cropped using that value.

More information about the options is available using the `--help` option.

**Comment by JMoVS** [comment]
As one is not actively examining the output of detect-crop manually, and as transcode-video has the option to pass "--crop detect" to get the behaviour of detect-crop, I think we should change this to rip out the logic for detect-crop parsing and instead use the built-in crop detection (which would also make it easier to supply crop values as you don't have to "force" it anymore and can specify for example which one should be the fallback crop in case of conflict.

Can you point me to the relevant code bits and also maybe where I could read up on how I get a working development environment for this script going? I'd try to rip that out and then submit a pull request.

**Comment by nwronski** [comment]
Sure, the crop detection happens [here](https://github.com/nwronski/batch-transcode-video/blob/master/lib/video-file.js#L111).

**Comment by JMoVS** [comment]
I'm sorry, I can't do this. It would be great if I could disable crop parameters that are passed from this script and instead use @donmelton's --crop detect and fallback_crop parameters then as additional parameters instead. Would that be a lot of work?

**Comment by nwronski** [comment]
try out the `--nocrop` option in [v2.0.0](https://github.com/nwronski/batch-transcode-video/releases/tag/v2.0.0) to disable `batch-transcode-video`'s crop detection logic. you could also use `--nocrop` in combination with custom options for `transcode-video`:

```
batch-transcode-video --input source/ --output finished/ --nocrop -- --crop detect
```

**Comment by JMoVS** [comment]
that's exactly why I wanted this option. I now use `--nocrop -- --crop detect`with the fallback crop set to minimal ;-)
